# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: afanneau <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/04 12:40:20 by afanneau          #+#    #+#              #
#    Updated: 2016/11/04 12:41:06 by afanneau         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c

OFILES = ft_display_file.o

HFILES = ft_display_file.h

all: $(NAME)

$(NAME):
		gcc -o $(NAME) $(SRC)
clean:
		rm -f $(OFILES)
fclean: clean
		rm -f $(NAME)
